id: dump_appointments_redshift
namespace: healthsynth.hospital
description: |
  Upload appointments data to AWS S3 and then load it into Redshift

labels:
  tag: appointments_dump

inputs:
  - id: appointments_data
    type: URI

  - id: current_date
    type: DATE

tasks:
  - id: upload_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "ap-south-1"
    from: "{{ inputs.appointments_data }}"
    bucket: "kestra-bucketv1"
    key: "appointments/{{ inputs.current_date }}/appointments.csv"

  - id: create_table_in_redshift
    type: io.kestra.plugin.jdbc.redshift.Query
    url: "jdbc:redshift://{{ secret('REDSHIFT_HOST') }}.amazonaws.com:5439/dev"
    username: "{{ secret('REDSHIFT_USER') }}"
    password: "{{ secret('REDSHIFT_PASSWORD') }}"
    sql: |
      CREATE TABLE IF NOT EXISTS appointments (
        AppointmentID VARCHAR(10) PRIMARY KEY,
        PatientID VARCHAR(10),
        DoctorID VARCHAR(10),
        ScheduledDay DATE,
        AppointmentDay DATE,
        NoShow BOOLEAN
      );

  - id: import_to_redshift
    type: io.kestra.plugin.jdbc.redshift.Query
    url: "jdbc:redshift://{{ secret('REDSHIFT_HOST') }}.amazonaws.com:5439/dev"
    username: "{{ secret('REDSHIFT_USER') }}"
    password: "{{ secret('REDSHIFT_PASSWORD') }}"
    sql: |
      COPY appointments
      FROM 's3://kestra-bucketv1/appointments/{{ inputs.current_date }}/appointments.csv'
      IAM_ROLE 'arn:aws:iam::774305599848:role/redshift-kestra'
      CSV
      DELIMITER ','
      IGNOREHEADER 1;

triggers:
  - id: dump_appointments_trigger
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      appointments_data: "{{ outputs.go_script.outputFiles['appointments.csv'] }}"
      current_date: "{{ outputs.run_date.value }}"
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: healthsynth.hospital
        flowId: data_gen
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
